CREATE TABLE [dbo].[Stages]
(
  StageId     INT IDENTITY(1,1) PRIMARY KEY,
  StageKey    VARCHAR(40) UNIQUE NOT NULL,  -- APPLIED, INT1, INT2, INT3_5, OFFER, HIRED, REJECTED, NO_RESPONSE
  DisplayName VARCHAR(100) NOT NULL,
  SortOrder   INT NOT NULL
);